version: "3.9"

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - ./src:/code/src
      - ./tests:/code/tests
    depends_on:
      - postgres
    env_file:
      - envs/.env

  postgres:
    container_name: bookservice-postgres
    image: postgres:15.4-alpine
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - envs/postgres.env
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  backend-data:
    name: backend-data
  postgres-data:
    name: postgres-data