"""unique

Revision ID: 52e5b25e3503
Revises: dd93cf96037f
Create Date: 2023-09-27 13:24:57.372237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52e5b25e3503'
down_revision: Union[str, None] = 'dd93cf96037f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('name', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'books', ['name'])
    op.drop_column('books', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'books', type_='unique')
    op.drop_column('books', 'name')
    # ### end Alembic commands ###
